---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - vendor/**/*
    - gemfiles/vendor/**/*

Naming/FileName:
  Exclude:
    - lib/ar-check.rb

Metrics/LineLength:
  Exclude:
    - ar-check.gemspec
    - test/**/*_test.rb

Metrics/MethodLength:
  Enabled: false
