language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler
before_script:
  - createdb test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
gemfile:
  - Gemfile
  - gemfiles/activerecord_5_1.gemfile
  - gemfiles/activerecord_5_0.gemfile
rvm:
  - 2.5.3
notifications:
  email: false
env:
  global:
    secure: TXvbcbVjNOjtxUI1ckKuPVtFv7uSlzh05ayUzS1tZuanZgG2hDLpBQMR79O55Ag9isVk5iGWg9CLalBtoIyp6chhxf/GOrn2PXUroOFmpZMvSrBZbDq+ZBUl7/5xm11GLv/wainQJG1nE/M3TcHm+CaPygPoow8ngpEANRfG4dzZa00eu9HZUahlxC2vLBcjvDG7uVMpnPCqFsOyUPiiBu3pGfmUsaeZ08GbTLbhy0GWnbYQ9gf6mWXmG6iVdNiJ4T2ftsicVqfTOSclSjkCfsCMn+Zh5BjSimEY8mv6YG/gSxlXyLD1cNRWDZPo262l7xg4W05Bp5axR6/VD7PljQpOEeFef5KZvPR/8O1A/XyN2BRyVEaHhGV1vfgEzcVLITdnfH3N2++dfVmkb7NcGFTF/tY2SxttdEAwNq/Ai0bUeaocpzGOepqc+JR3cjfswQJp5OqYXn7+beIydMYLzx7jT9n5Ju27y4wtqFSWjof9NgGq5STXKpAUrk6TqlOVwySwiiLH5mxjCfWmFyyucrIHTqUky6W1NnLJJlHJPfrFMhCbiANsSnsF8GWwwAM9ECoG2dcBCDjpinrzFFpilFes8wCZ6WauRyuUe9Xsk37oSIx7R5s67rYB5VQVr2PqlGZurcyjdoy2sR/c7vbblEI9kSV2YxsivNHO0QItc0Q=
